### ISSUE TITLE
Getting errors related to "any" types when accessing env variables

### ISSUE THREAD

**Issue by Alex-Mastin** [t3-oss/t3-env#153]
For some reason I'm getting type errors when trying to access env variables. My config is generated from `create-t3-app` so I don't think it should be incorrect. I've checked the documentation several times, but still can't understand why this is giving me type errors. 

TypeScript version: `^5.1.6`
t3-env version: `^0.6.1`

### env.mjs
```js
import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'test', 'production']),
    BASE_URL: z.string().min(1).startsWith('http')
  },
  client: {},
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    BASE_URL: process.env.BASE_URL
  }.
  skipValidation: !!process.env.SKIP_ENV_VALIDATION
})
```

### .env
```js
BASE_URL="..."
```

### SomeComponent.tsx
```tsx
export default async function SomeComponent() {
  // ESLint: Unsafe assignment of an `any` value.(@typescript-eslint/no-unsafe-assignment)
  const BASE_URL = env.BASE_URL
  
  // ESLint: Invalid type "any" of template literal expression.(@typescript-eslint/restrict-template-expressions)
  const response = await fetch(`${BASE_URL}`)
  
  ...

  return (
    ...
  )
}
```

Am I just doing something wrong here? It works fine when I try `NODE_ENV`.

**Comment by chungweileong94** [comment]
Mind if you can provide a small repo for this issue? It might be related to some other type-issues reported by others, which I wasn't able to reproduce myself🫤

**Comment by Alex-Mastin** [comment]
Unfortunately I'm having this issue in a private work repo :(

**Comment by chungweileong94** [comment]
> Unfortunately I'm having this issue in a private work repo :(

I mean, is it possible for you to create a simple repro to replicate the issue?

**Comment by juliusmarminge** [comment]
resolved in 0.7, else reopen

**Comment by pjborowiecki** [comment]
Same problem here. I am using it with Next.js, everything works great with 0.7.3, but as soon as I upgrade @t3-oss/env-nextjs to the latest version (0.9.2), I am getting "any" type errors for all my variables and the entire env.mjs is covered in red squiggly lines.

Here are my package versions:

```
"dependencies": {
    "@hookform/resolvers": "^3.3.4",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-toast": "^1.1.5",
    "@react-email/components": "^0.0.14",
    "@t3-oss/env-nextjs": "^0.7.3",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "dotenv": "^16.4.4",
    "next": "14.1.0",
    "next-themes": "^0.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-email": "^2.0.0",
    "react-hook-form": "^7.50.1",
    "react-wrap-balancer": "^1.1.0",
    "resend": "^3.2.0",
    "tailwind-merge": "^2.2.1",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@ianvs/prettier-plugin-sort-imports": "^4.1.1",
    "@tailwindcss/line-clamp": "^0.4.4",
    "@tailwindcss/typography": "^0.5.10",
    "@types/eslint": "^8.56.2",
    "@types/node": "^20.11.17",
    "@types/react": "^18.2.55",
    "@types/react-dom": "^18.2.19",
    "@typescript-eslint/eslint-plugin": "^7.0.1",
    "@typescript-eslint/parser": "^7.0.1",
    "autoprefixer": "^10.4.17",
    "eslint": "^8.56.0",
    "eslint-config-next": "14.1.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-tailwindcss": "^3.14.2",
    "postcss": "^8.4.35",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.5.11",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.3.3"
  },
```

**Comment by juliusmarminge** [comment]
have you made sure your tsconfig supports esm only packages, i.e. can read package.json#exports? 0.9 was a breaking change dropping support for cjs module resolution

**Comment by Kirushan-Balakrishnan** [comment]
> Same problem here. I am using it with Next.js, everything works great with 0.7.3, but as soon as I upgrade @t3-oss/env-nextjs to the latest version (0.9.2), I am getting "any" type errors for all my variables and the entire env.mjs is covered in red squiggly lines.
> 
> Here are my package versions:
> 
> ```
> "dependencies": {
>     "@hookform/resolvers": "^3.3.4",
>     "@radix-ui/react-icons": "^1.3.0",
>     "@radix-ui/react-slot": "^1.0.2",
>     "@radix-ui/react-toast": "^1.1.5",
>     "@react-email/components": "^0.0.14",
>     "@t3-oss/env-nextjs": "^0.7.3",
>     "class-variance-authority": "^0.7.0",
>     "clsx": "^2.1.0",
>     "dotenv": "^16.4.4",
>     "next": "14.1.0",
>     "next-themes": "^0.2.1",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "react-email": "^2.0.0",
>     "react-hook-form": "^7.50.1",
>     "react-wrap-balancer": "^1.1.0",
>     "resend": "^3.2.0",
>     "tailwind-merge": "^2.2.1",
>     "tailwindcss-animate": "^1.0.7",
>     "zod": "^3.22.4"
>   },
>   "devDependencies": {
>     "@ianvs/prettier-plugin-sort-imports": "^4.1.1",
>     "@tailwindcss/line-clamp": "^0.4.4",
>     "@tailwindcss/typography": "^0.5.10",
>     "@types/eslint": "^8.56.2",
>     "@types/node": "^20.11.17",
>     "@types/react": "^18.2.55",
>     "@types/react-dom": "^18.2.19",
>     "@typescript-eslint/eslint-plugin": "^7.0.1",
>     "@typescript-eslint/parser": "^7.0.1",
>     "autoprefixer": "^10.4.17",
>     "eslint": "^8.56.0",
>     "eslint-config-next": "14.1.0",
>     "eslint-config-prettier": "^9.1.0",
>     "eslint-plugin-tailwindcss": "^3.14.2",
>     "postcss": "^8.4.35",
>     "prettier": "^3.2.5",
>     "prettier-plugin-tailwindcss": "^0.5.11",
>     "tailwindcss": "^3.4.1",
>     "typescript": "^5.3.3"
>   },
> ```

yes 0.7.3 working perfectly and 0.9.2 giving the type errors

**Comment by brandanking-decently** [comment]
@juliusmarminge this needs reopening. On the latest versions this is still an issue

**Comment by Keeqler** [comment]
I have the same issue on 0.10.1

**Comment by juliusmarminge** [comment]
Can almost guarantee it's not a problem with the lib but that you dont have a supported moduleResolution set

**Comment by Keeqler** [comment]
> Can almost guarantee it's not a problem with the lib but that you dont have a supported moduleResolution set but without a repro there's no way to tell

I can confirm that's the issue. Setting `moduleResolution` to `Bundler` did the trick. Thank you!

**Comment by MiroStW** [comment]
I still have the issue, even though I used create-t3-app with unmodified tsconfig
